#!/bin/bash

VMSTAT=$(vm_stat)

FREE_BLOCKS=$(echo "$VMSTAT" | grep free | awk '{ print $3 }' | sed 's/\.//')
INACTIVE_BLOCKS=$(echo "$VMSTAT" | grep inactive | awk '{ print $3 }' | sed 's/\.//')
SPECULATIVE_BLOCKS=$(echo "$VMSTAT" | grep speculative | awk '{ print $3 }' | sed 's/\.//')

FREE=$(((FREE_BLOCKS+SPECULATIVE_BLOCKS)*4096/1048576))
INACTIVE=$((INACTIVE_BLOCKS*4096/1048576))
TOTAL=$(((FREE+INACTIVE)))
echo "scale=2; ${TOTAL}/1024" | bc
